/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Point;
import java.awt.event.ActionEvent;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.opencv.core.Core;

/**
 *
 * @author izyde
 */
public class main extends javax.swing.JFrame {

    JFileChooser fc = new JFileChooser();
    
    FileNameExtensionFilter filter = null;
    
    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        nu.pattern.OpenCV.loadShared();
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        openFile = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        closeAllWindow = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        helpMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        openFile.setText("Abrir archivo");
        openFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileActionPerformed(evt);
            }
        });
        jMenu1.add(openFile);

        exit.setText("Salir");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edición");

        closeAllWindow.setText("Cerrar ventanas");
        closeAllWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeAllWindowActionPerformed(evt);
            }
        });
        jMenu2.add(closeAllWindow);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");

        helpMenu.setText("Acerca de");
        helpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpMenuActionPerformed(evt);
            }
        });
        jMenu3.add(helpMenu);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeAllWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeAllWindowActionPerformed
        JInternalFrame[] vectorVentanas = Desktop.getAllFrames();
        for(JInternalFrame ventana : vectorVentanas){
            ventana.dispose();
        }
    }//GEN-LAST:event_closeAllWindowActionPerformed

    private void helpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpMenuActionPerformed
        JOptionPane.showMessageDialog(rootPane, "En el menú Archivo dispondrá de 2 opciones: Abrir Archivo y Salir.\n"
                + "Abrir Archivo permite abrir una imagen en una ventana dentro de la aplicación.\n"
                + "Salir, cerrará la aplicación.\n\n"
                + "En el menú Edición dispondrá de la opción de Cerrar Ventanas\n"
                + "Al igual que cuando se intenta abrir una segunda imagen, se cerrarán todas la ventanas abiertas\n\n"
                + "Dentro de cada ventana se dispone de 2 submenús, Archivo y Edición\n"
                + "Archivo permite Guardar la imagen en su equipo y Cerrar cerrará la ventana seleccionada\n"
                + "Edición permite modificar la imagen mediante el proceso de umbralizado\n"
                + "creando una nueva ventana con el resultado obtenido\n\n"
                + "Desarrollado por: Noah Hernández Morales e Isidro Bermúdez Fernández", "Ayuda", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_helpMenuActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        int screenWidth = getWidth();
        int screenHeight = getHeight();
        Desktop.setSize(screenWidth, screenHeight);
        JInternalFrame[] vectorVentanas = Desktop.getAllFrames();
        for(JInternalFrame ventana : vectorVentanas){
            Point loc = ventana.getLocation();
            if(loc.x >= screenWidth || loc.y >= screenHeight){
                ventana.setLocation(0,0);
            }
        }
    }//GEN-LAST:event_formComponentResized

    private void openFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileActionPerformed
        filter = new FileNameExtensionFilter("Imágenes", "png", "jpg", "jpge");
        fc.addChoosableFileFilter(filter);
        
        int res = fc.showOpenDialog(null);
        if(res == JFileChooser.APPROVE_OPTION){
            if(Desktop.getAllFrames().length != 0){
                int resInt = JOptionPane.showConfirmDialog(rootPane, "Continuar eliminará cualquier cambio no guardado. ¿Seguro que quieres continuar?", "Abrir", JOptionPane.YES_NO_OPTION);
                if(resInt == JOptionPane.YES_OPTION){
                    closeAllWindowActionPerformed(evt);
                    File fichero = fc.getSelectedFile();
                    VentanaInterna ventana = new VentanaInterna();
                    ventana.setTitle(fichero.getName());
                    Desktop.add(ventana);
                    ventana.setLocation(new Point(30,20));
                    ventana.getImagePanel().AddImage(fichero);
                    ventana.setVisible(true);
                }
            } else{
                File fichero = fc.getSelectedFile();
                VentanaInterna ventana = new VentanaInterna();
                ventana.setTitle(fichero.getName());
                Desktop.add(ventana);
                ventana.setLocation(new Point(30,20));
                ventana.getImagePanel().AddImage(fichero);
                ventana.setVisible(true);
            }
        }
    }//GEN-LAST:event_openFileActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        int res = JOptionPane.showConfirmDialog(rootPane, "¿Seguro que quieres salir?", "Salir", JOptionPane.YES_NO_OPTION);
        
        if(res == JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_exitActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int res = JOptionPane.showConfirmDialog(rootPane, "¿Seguro que quieres salir?", "Salir", JOptionPane.YES_NO_OPTION);
        
        if(res == JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem closeAllWindow;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenuItem helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem openFile;
    // End of variables declaration//GEN-END:variables
}
